package com.mlx.accounts.model;

/**
 * 10/5/14.
 */
public enum EventType {
    REGISTRATION,
    DUPLICATE_REGISTRATION,
    ACTIVATION, SIGNON, SIGNON_FAIL,

    SKILL_ADDED, SKILL_UPDATED,

    INTERVIEW_CREATED, INTERVIEW_CANCELED, INTERVIEW_REJECTED,
    INTERVIEW_APPROVED, INTERVIEW_DONE, INTERVIEW_REMOVED,
    INTERVIEW_MESSAGE, INTERVIEW_CODE_CHECK, INTERVIEW_READ,

    LINKED_IN_CONNECT, LINKED_IN_SIGNON, LINKED_IN_UPDATE,
    FACEBOOK_IN_CONNECT, FACEBOOK_IN_SIGNON, FACEBOOK_IN_UPDATE,
    GOOGLE_IN_CONNECT, GOOGLE_IN_SIGNON, GOOGLE_IN_UPDATE,
    GITHUB_IN_CONNECT, GITHUB_IN_SIGNON, GITHUB_IN_UPDATE,

    SELF_REMOVAL, DELETE_USER, DELETE_SKILL, DELETE_ALL_SKILLS, DELETE_ALL_USERS
}
